import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";

// The compiler runs Samva's exactly pinned Tailwind, never the template
// project's copy: a build must not execute code downloaded from the project's
// locked graph. Tailwind's stylesheets are files rather than module exports, so
// they are copied in here at codegen time and the resulting module travels
// inside the compiler bundle — the same bytes in the Vite adapter, the hosted
// build and the isolated worker.

const require = createRequire(import.meta.url);
const root = dirname(require.resolve("tailwindcss/package.json"));
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8")) as {
  version: string;
};
const read = (name: string) => readFileSync(join(root, name), "utf8");

const source = `// Generated by scripts/codegen-tailwind.ts from tailwindcss@${manifest.version}.
// Do not edit; run \`bun run --filter @samva/markup codegen:tailwind\` after a version bump.

/** The exact Tailwind release the compiler runs, recorded in every build manifest. */
export const TAILWIND_VERSION = ${JSON.stringify(manifest.version)};

/** \`tailwindcss/theme.css\` — the default \`@theme\` custom properties. */
export const TAILWIND_THEME_CSS = ${JSON.stringify(read("theme.css"))};

/** \`tailwindcss/utilities.css\` — the directive that expands to matched utilities. */
export const TAILWIND_UTILITIES_CSS = ${JSON.stringify(read("utilities.css"))};

/**
 * \`tailwindcss/preflight.css\` — a browser reset. It is not part of the default
 * email entry: its \`*\` and element rules would inline onto every node and its
 * assumptions do not hold in an email client. A project can opt in explicitly.
 */
export const TAILWIND_PREFLIGHT_CSS = ${JSON.stringify(read("preflight.css"))};
`;

writeFileSync(new URL("../src/email/tailwind-stylesheets.gen.ts", import.meta.url), source);
process.stdout.write(`tailwind-stylesheets.gen.ts written from tailwindcss@${manifest.version}\n`);
