import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { assetEntry, assetUrl } from "../src/email/assets";
import {
  checkEmailCompatibility,
  COMPATIBILITY_PROVENANCE,
  EMAIL_CLIENT_MATRIX,
} from "../src/email/compatibility";
import { parseStylesheet } from "../src/email/css";
import { serializeEmailHtml } from "../src/email/html";
import { compileTailwind } from "../src/email/tailwind";
import {
  CAMPAIGN_CLASSES,
  COMPATIBILITY_CORPUS,
  type CorpusCase,
} from "../tests/fixtures/email-compatibility-corpus";
import { registerStylesheet, resetStylesheets } from "../tests/support/stylesheet-registry";

// Renders the compatibility corpus for the two audiences that need it.
//
//   browser/  files to open from disk. Assets resolve against a relative base,
//             and the imported binary is written beside them.
//   email/    files to send. Images are external https URLs only, because a mail
//             client cannot resolve a relative base and will not fetch a file
//             path — so the case that imports a local binary is not here.
//
// Run: bun run --filter @samva/markup corpus:render [outputDirectory]

const output =
  process.argv[2] ?? join(import.meta.dirname, "..", "tests", "output", "compatibility");
const browserDirectory = join(output, "browser");
const emailDirectory = join(output, "email");
const assetsDirectory = join(browserDirectory, "assets");

/** A 1x1 transparent PNG: real bytes, so the asset is addressed by real content. */
const PIXEL = Uint8Array.from(
  atob(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==",
  ),
  (character) => character.codePointAt(0) ?? 0,
);

const render = async (entry: CorpusCase, logoUrl: string) => {
  resetStylesheets();
  if (entry.id === "campaign-responsive-dark") {
    const compiled = await compileTailwind(CAMPAIGN_CLASSES);
    registerStylesheet(parseStylesheet(compiled.css, { origin: "tailwind" }));
  }
  // The one case whose image comes from the project itself needs the base the
  // export will actually serve from.
  const input = entry.id === "branded-local-asset" ? { name: "Ada", logoUrl } : entry.input;
  // Only the export-only case may reference a relative base; everything that
  // can be sent is rendered exactly as it would be delivered.
  const rendered = entry.render(input, {
    relativeUrls: !entry.emailable,
  });
  const emitted = serializeEmailHtml(rendered.tree);
  const findings = checkEmailCompatibility({
    html: emitted.html,
    positions: emitted.positions,
  });
  return { rendered, findings };
};

rmSync(output, { recursive: true, force: true });
mkdirSync(assetsDirectory, { recursive: true });
mkdirSync(emailDirectory, { recursive: true });

const asset = await assetEntry("assets/logo.png", PIXEL);
writeFileSync(join(assetsDirectory, asset.fileName), PIXEL);
const relativeBase = "./assets";
const logoUrl = assetUrl(asset, relativeBase);

const rows: string[] = [];
for (const entry of COMPATIBILITY_CORPUS) {
  const { rendered, findings } = await render(entry, logoUrl);
  const blocking = findings.filter((finding) => finding.severity === "error");
  const warnings = findings.filter((finding) => finding.severity === "warning");
  writeFileSync(join(browserDirectory, `${entry.id}.html`), rendered.html);
  writeFileSync(join(browserDirectory, `${entry.id}.txt`), rendered.text);
  if (entry.emailable) {
    writeFileSync(join(emailDirectory, `${entry.id}.html`), rendered.html);
    writeFileSync(join(emailDirectory, `${entry.id}.txt`), rendered.text);
    writeFileSync(
      join(emailDirectory, `${entry.id}.subject.txt`),
      `${rendered.subject}\n${rendered.preheader ?? ""}\n`,
    );
  }
  rows.push(
    `| \`${entry.id}\` | ${entry.title} | ${entry.emailable ? "yes" : "no — local asset base"} | ${blocking.length} | ${warnings.length} |`,
  );
}

writeFileSync(
  join(browserDirectory, "assets", "manifest.json"),
  `${JSON.stringify({ base: relativeBase, assets: [asset] }, null, 2)}\n`,
);

const record = `# Compatibility corpus

Generated by \`bun run --filter @samva/markup corpus:render\`. Do not edit; regenerate.

Rules: ${COMPATIBILITY_PROVENANCE.rules}, caniemail data ${COMPATIBILITY_PROVENANCE.apiVersion},
last updated ${COMPATIBILITY_PROVENANCE.lastUpdate}.

Pinned client matrix: ${EMAIL_CLIENT_MATRIX.map((target) => target.label).join(", ")}.

## Cases

| id | what it is | emailable | blocking | warnings |
| --- | --- | --- | --- | --- |
${rows.join("\n")}

\`browser/\` opens from disk; its images resolve against the relative \`./assets\`
base written beside them. \`email/\` is the set that can be sent: every image in
it is an external https URL, because a mail client cannot resolve a relative
base and will not fetch a file path.

## What these checks do and do not establish

Static checks read the emitted HTML and CSS against caniemail's pinned data.
They establish that a construct is documented as unsupported, partially
supported, or undocumented for a target client. They do not establish how a
client renders a document, because the data describes features, not layout.

Settled by the static checks:

- a construct a target client drops entirely, which blocks publication
- a construct that degrades gracefully, which warns
- partial support, with the note that says what is partial
- constructs the pinned data says nothing about, reported as unknown coverage

Not settled by them, and only answerable in a real client:

- whether the classic Outlook VML button draws at the intended size and colour
- whether Gmail's forced dark inversion leaves text readable over its background
- whether the responsive breakpoint actually stacks, since Gmail supports
  \`@media\` only partially and Outlook Windows not at all
- whether a preheader is what the inbox list shows, and where it stops
- whether table-based columns hold at real client widths
- how a client wraps long unbroken strings and non-Latin text
- whether an external image loads before the recipient allows remote content
`;

writeFileSync(join(output, "README.md"), record);
process.stdout.write(`Wrote the compatibility corpus to ${output}\n`);
